CREATE TABLE crew_members
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    role    VARCHAR(255)                            NOT NULL,
    status  VARCHAR(255)                            NOT NULL,
    ship_id BIGINT,
    CONSTRAINT pk_crew_members PRIMARY KEY (id)
);

CREATE TABLE ports
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    capacity INTEGER                                 NOT NULL,
    CONSTRAINT pk_ports PRIMARY KEY (id)
);

CREATE TABLE ships
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    min_crew_capacity INTEGER                                 NOT NULL,
    max_crew_capacity INTEGER                                 NOT NULL,
    port_id           BIGINT,
    CONSTRAINT pk_ships PRIMARY KEY (id)
);

ALTER TABLE ships
    ADD CONSTRAINT uc_ships_name UNIQUE (name);

ALTER TABLE ships
    ADD CONSTRAINT FK_SHIPS_ON_PORT FOREIGN KEY (port_id) REFERENCES ports (id);

ALTER TABLE crew_members
    ADD CONSTRAINT FK_CREW_MEMBERS_ON_SHIP FOREIGN KEY (ship_id) REFERENCES ships (id);

INSERT INTO ports (capacity, name)
VALUES (5, 'Дальний'),
       (10, 'Солнечный'),
       (7, 'Восточный');

INSERT INTO ships (max_crew_capacity, min_crew_capacity, name, status, port_id)
VALUES (5, 2, 'Проворный', 'SEA', NULL),
       (5, 2, 'Санта Мария', 'PORT', 1),
       (5, 2, 'Туман', 'PORT', 2),
       (5, 2, 'Буря', 'PORT', 2),
       (5, 2, 'Сказочный', 'PORT', 2),
       (5, 2, 'Грозный', 'PORT', 3),
       (5, 2, 'Восток', 'PORT', 3),
       (5, 2, 'Кудесник', 'PORT', 3),
       (5, 2, 'Арктика', 'PORT', 3),
       (5, 2, 'Москва', 'PORT', 2);

INSERT INTO crew_members (status, name, role, ship_id)
VALUES ('ON_SHIP', 'Ivan', 'CAPITAN', 1),
       ('ON_LAND', 'Anton', 'CAPITAN', null),
       ('ON_SHIP', 'Slava', 'MATE', 1),
       ('ON_SHIP', 'Dima', 'MATE', 1),
       ('ON_SHIP', 'Maksim', 'MATE', 2),
       ('ON_SHIP', 'Jenya', 'MATE', 2);