version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgresportdb

  postgresportdb:
    image: 'postgres:15'
    volumes:
      - ./init/test-data.sql:/docker-entrypoint-initdb.d/test_data.sql
    container_name: 'docker-port-app'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust